Bump to react 19 with specifying es2022 forn esm.sh target
If not adding this or adding denonext, it failed with following error

error: Uncaught (in promise) Error: Unable to output during bundling: load_transformed failed: failed to analyze module: failed to resolve node:process from https://esm.sh/react@19.0.0/denonext/react.mjs: Cannot resolve "node:process